# Generated by Django 3.1.4 on 2020-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_delete_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='characterisation',
        ),
        migrations.AddField(
            model_name='sample',
            name='characterisation',
            field=models.ManyToManyField(to='catalogue.Analysis'),
        ),
    ]
